import type { Material } from "./schemas";

// ===========================================================
// CSV export, formatted to drop into Sigma-Aldrich's bulk-order
// portal (and similar enterprise procurement tools).
//
// Column shape Sigma's bulk uploader accepts:
//   Catalog Number, Quantity, Unit, Description, Notes
//
// We additionally emit Supplier and unit pricing so a procurement
// manager can split lines across vendors.
// ===========================================================

function csvCell(v: string | number | null | undefined): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function materialsToOrderSheetCsv(materials: Material[], hypothesis = ""): string {
  const lines: string[] = [];
  lines.push(`# Order sheet generated by The AI Scientist`);
  if (hypothesis) lines.push(`# Hypothesis: ${hypothesis.slice(0, 300).replace(/\n/g, " ")}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push(`# Format: Sigma-Aldrich bulk-upload compatible (Catalog#, Quantity)`);
  lines.push("");
  const header = [
    "Catalog Number",
    "Quantity",
    "Unit",
    "Description",
    "Supplier",
    "Category",
    "Unit Cost (USD)",
    "Total Cost (USD)",
    "URL",
    "Notes",
  ];
  lines.push(header.join(","));

  for (const m of materials) {
    const qty = (m.quantity || "").trim();
    // Try to split "1 case" / "100 mL" / "25 g" / "vial" → numeric + unit
    const numMatch = qty.match(/^(\d+(?:\.\d+)?)/);
    const numericQty = numMatch ? numMatch[1] : "1";
    const unit = numMatch ? qty.slice(numMatch[0].length).trim() || "EA" : qty || "EA";

    lines.push(
      [
        csvCell(m.catalog_number ?? ""),
        csvCell(numericQty),
        csvCell(unit),
        csvCell(m.name),
        csvCell(m.supplier),
        csvCell(m.category),
        csvCell(m.unit_cost_usd?.toFixed(2) ?? ""),
        csvCell(m.total_cost_usd?.toFixed(2) ?? ""),
        csvCell(m.url ?? ""),
        csvCell(m.notes ?? ""),
      ].join(",")
    );
  }
  // Trailing total
  const total = materials.reduce((s, m) => s + (m.total_cost_usd ?? 0), 0);
  lines.push("");
  lines.push(`# Total materials cost (USD), ${total.toFixed(2)}`);
  return lines.join("\n");
}
